version: '2'
services:
  web:
    build: .
    volumes:
      - ./src/flashcards/:/app
    environment: 
      DB_PASSWORD: ElPolloDiablo!
      DEBUG: 'true'
    ports:
      - "8000:8000"
    depends_on:
      - flashcards-db
  flashcards-db:
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ItWasTheBestOfTimes
      MYSQL_USER: flashcards
      MYSQL_PASSWORD: ElPolloDiablo!
      MYSQL_DATABASE: flashcards
  # flashcards-search:
    # image: elasticsearch