# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(max_length=500)),
                ('bucket_number', models.IntegerField(default=0)),
                ('visible_after', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('failure_count', models.IntegerField(default=0)),
            ],
        ),
    ]
