# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160819_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='visible_after',
            field=models.DateTimeField(),
        ),
    ]
